import { Router } from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import User from '../models/User.js';
import { protect } from '../middleware/auth.js';
const router = Router();
const tokenFor = id => jwt.sign({ id }, process.env.JWT_SECRET, { expiresIn:'7d' });
router.post('/register', async (req,res,next) => { try { const { name,email,password,location,profileImage } = req.body; if (!name || !email || !password || !location) return res.status(400).json({message:'Name, email, password and location are required'}); if (await User.findOne({email})) return res.status(409).json({message:'Email is already registered'}); const user=await User.create({name,email,password:await bcrypt.hash(password,12),location,profileImage}); res.status(201).json({ token:tokenFor(user.id), user:{...user.toObject(),password:undefined} }); } catch(e){next(e)} });
router.post('/login', async (req,res,next) => { try { const user=await User.findOne({email:req.body.email}).select('+password'); if (!user || !(await bcrypt.compare(req.body.password,user.password))) return res.status(401).json({message:'Invalid email or password'}); res.json({token:tokenFor(user.id),user:{...user.toObject(),password:undefined}}); } catch(e){next(e)} });
router.get('/me',protect,(req,res)=>res.json(req.user));
export default router;
