import { Router } from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import User from '../models/User.js';
import { protect } from '../middleware/auth.js';
const router = Router();
const tokenFor = id => jwt.sign({ id }, process.env.JWT_SECRET, { expiresIn:'7d' });
const validEmail = email => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
router.post('/register', async (req,res,next) => { try { const name=String(req.body.name||'').trim(); const email=String(req.body.email||'').trim().toLowerCase(); const password=String(req.body.password||''); const location=String(req.body.location||'').trim(); if (name.length<2 || name.length>80 || !validEmail(email) || password.length<8 || location.length<2) return res.status(400).json({message:'Enter a valid name, email, location, and password of at least 8 characters'}); if (await User.findOne({email})) return res.status(409).json({message:'Email is already registered'}); const user=await User.create({name,email,password:await bcrypt.hash(password,12),location,profileImage:req.body.profileImage}); res.status(201).json({ token:tokenFor(user.id), user:{...user.toObject(),password:undefined} }); } catch(e){next(e)} });
router.post('/login', async (req,res,next) => { try { const email=String(req.body.email||'').trim().toLowerCase(); const password=String(req.body.password||''); const user=await User.findOne({email}).select('+password'); if (!user || !(await bcrypt.compare(password,user.password))) return res.status(401).json({message:'Invalid email or password'}); res.json({token:tokenFor(user.id),user:{...user.toObject(),password:undefined}}); } catch(e){next(e)} });
router.get('/me',protect,(req,res)=>res.json(req.user));
router.get('/members',protect,async(req,res,next)=>{try{res.json(await User.find({_id:{$ne:req.user.id}}).select('name location profileImage').limit(20))}catch(e){next(e)}});
export default router;
